let teamData = {
  app: {
    sortCol: "name",
    sortDir: "asc",
  },
  data: [
    {
      id: 1,
      name: "BLQK Bears",
      coachName: "Ritchie Tuazon",
      coachPhone: "612-395-3039",
      players: [
        "Andrea Koop",
        "Maggie Brascia",
        "Dylan Frazier",
        "Federico Staksrud",
      ],
      logo: "img/blqk-logo.jpg",
    },
    {
      id: 2,
      name: "Florida Smash",
      coachName: "Travis Rettenmaier",
      coachPhone: "712-484-8089",
      players: [
        "Jessie Irvine",
        "Jorja Johnson",
        "Travis Rettenmaier",
        "Collin Johns",
      ],
      logo: "img/florida-smash-logo.png",
    },
    {
      id: 3,
      name: "Mad Drops",
      coachName: "Drew Brees",
      coachPhone: "636-258-8754",
      players: [
        "Catherine Parenteau",
        "Irina Tereschenko",
        "Julian Arnold",
        "Thomas Wilson",
      ],
      logo: "img/mad-drops-logo.png",
    },
    {
      id: 4,
      name: "ATX Pickleballers",
      coachName: "Brene Brown",
      coachPhone: "440-667-6161",
      players: [
        "Jackie Kawamoto",
        "Jade Kawamoto",
        "JW Johnson",
        "Gabriel Tardio",
      ],
      logo: "img/atx-logo.svg",
    },
    {
      id: 5,
      name: "Frisco Clean Cause",
      coachName: "Tim Berry",
      coachPhone: "440-667-6161",
      players: [
        "Yana Grechkina",
        "Lina Padegimaite",
        "Zane Navratil",
        "Matt Wright",
      ],
      logo: "img/clean-logo.png",
    },
    {
      id: 6,
      name: "Las Vegas Night Owls",
      coachName: "Grey Frady",
      coachPhone: "913-559-5534",
      players: ["Vivienne David", "Lauren Stratman", "Dekel Bar", "Kyle Yates"],
      logo: "img/night-owls-logo.png",
    },
    {
      id: 7,
      name: "Milwaukee Mashers",
      coachName: "Marc Lasry",
      coachPhone: "561-975-1200",
      players: [
        "Callie Jo SMith",
        "Lucia Kovalova",
        "Andrei Daescu",
        "DJ Young",
      ],
      logo: "img/mashers-logo.svg",
    },
    {
      id: 8,
      name: "New Jersey 5s",
      coachName: "Gary Vanerchuk",
      coachPhone: "203-498-1936",
      players: [
        "Anna Leigh Waters",
        "Lea Jansen",
        "Ignatowich",
        "Hayden Patriquin",
      ],
      logo: "img/5s-logo.jpg",
    },
    {
      id: 9,
      name: "New York Hustlers",
      coachName: "LeBron James",
      coachPhone: "561-776-9854",
      players: [
        "Anna Bright",
        "Lacy Schneemann",
        "Tyson McGuffin",
        "Rafa Hewett",
      ],
      logo: "img/hustlers-logo.png",
    },
    {
      id: 10,
      name: "Seattle Pioneers",
      coachName: "Ruslan Ever",
      coachPhone: "361-938-2213",
      players: ["Etta Wright", "Meghan Dizon", "Ben Johns", "Tyler Loong"],
      logo: "img/pioneers-logo.png",
    },
  ],
};

export default teamData;
